#https://docs.travis-ci.com/user/languages/cpp/
language: cpp
notifications:
  email: false

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
        
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-8
          packages:
            - clang-8
            - libstdc++-8-dev
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

before_install:
  - PARENTDIR=$(pwd)
  - mkdir $PARENTDIR/build
  - mkdir $PARENTDIR/autogen
  - date +%Y-%m-%d-%H:%M:%S > $PARENTDIR/autogen/buildinfo.txt  

install: 
  #- bash -x $PARENTDIR/dependencies/checkout.sh
  - cd $PARENTDIR/dependencies
  - git clone https://${CI_USER_TOKEN}@github.com/nlohmann/json.git
  - cd $PARENTDIR/build
  - cmake $PARENTDIR
  - time make >> $PARENTDIR/autogen/buildinfo.txt
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: ${GITREPO_TOKEN} # Set in the settings page of your repository, as a secure variable
  keep_history: true
  target_branch: autogen
  committer_from_gh: true
  name: innopearl
  on:
    branch: master
    
# command to run tests
script:
  #- $PARENTDIR/build/test_json
  - echo Done
